#!/bin/sh

export PRELOAD_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

usage() {
  echo "usage: build-bullet <subcommand>"
  echo
  echo "Available subcommands are:"
  echo "   drupal   Start your project."
  echo "   theme    Create an initial theme."
  echo
  echo "Try 'build <subcommand> help' for details."
}

main() {
  # We want at least one arugment.
  if [ $# -lt 1 ]; then
    usage
    exit 1
  fi

  # load common functionality
  . "$PRELOAD_DIR/build-common"

  # Get the sub command.
  SUBCOMMAND="$1"; shift

  # If we don't have the command, then display usage.
  if [ ! -e "$PRELOAD_DIR/build-$SUBCOMMAND" ]; then
    usage
    exit 1
  fi

  # Run file
  . "$PRELOAD_DIR/build-$SUBCOMMAND"


  SUBACTION="default"
  if [ "$1" != "" ] && { ! echo "$1" | grep -q "^-"; } then
    SUBACTION="$1"; shift
  fi
  if ! type "cmd_$SUBACTION" >/dev/null 2>&1; then
    warn "Unknown subcommand: '$SUBACTION'"
    usage
    exit 1
  fi

  # Run subcommand.
  cmd_$SUBACTION "$@"
}

main "$@"
