#!/bin/sh

export KAFFE_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")


usage() {
  echo "usage: kaffe-bullet <subcommand>"
  echo
  echo "Available subcommands are:"
  echo "   init     Start your project."
  echo
  echo "Try 'kaffe <subcommand> help' for details."
}

main() {
  # We want at least one arugment.
  if [ $# -lt 1 ]; then
    usage
    exit 1
  fi

    # load common functionality
    . "$KAFFE_DIR/kaffe-common"

  # Get the sub command.
  SUBCOMMAND="$1"; shift

  # If we don't have the command, then display usage.
  if [ ! -e "$KAFFE_DIR/kaffe-$SUBCOMMAND" ]; then
    usage
    exit 1
  fi

  # Run file
  . "$KAFFE_DIR/kaffe-$SUBCOMMAND"


  SUBACTION="default"
  if [ "$1" != "" ] && { ! echo "$1" | grep -q "^-"; } then
    SUBACTION="$1"; shift
  fi
  if ! type "cmd_$SUBACTION" >/dev/null 2>&1; then
    warn "Unknown subcommand: '$SUBACTION'"
    usage
    exit 1
  fi

  # Run subcommand.
  cmd_$SUBACTION "$@"
}

main "$@"
