#!/bin/bash

cmd_default() {
  site_install
  drush_scripts
  enable_modules
  drush_scripts_post
}

site_install() {

echo '         __   __  ____      _                 _   _  __   __'
echo '        / /  / / |  _ \ ___| | ___   __ _  __| | | | \ \  \ \'
echo '       / /  / /  | |_) / _ \ |/ _ \ / _` |/ _` | | |  \ \  \ \'
echo '       \ \  \ \  |  _ <  __/ | (_) | (_| | (_| | |_|  / /  / /'
echo '        \_\  \_\ |_| \_\___|_|\___/ \__,_|\__,_| (_) /_/  /_/'
echo '         _ _                 _           _        _ _'
echo '     ___(_) |_ ___          (_)_ __  ___| |_ __ _| | | ___ _ __'
echo '    / __| | __/ _ \  _____  | | `_ \/ __| __/ _` | | |/ _ \ `__|'
echo '    \__ \ | ||  __/ |_____| | | | | \__ \ || (_| | | |  __/ |'
echo '    |___/_|\__\___|         |_|_| |_|___/\__\__,_|_|_|\___|_|'
echo '     _   _   _   _   _   _   _   _   _   _   _   _   _   _   _'
echo '    (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_) (_)'
echo ' '

  # Get the name of the site.
  echo "What is the site name?"
  read site_name

  if [ -z "$site_name" ]
  then
    site_name='default'
    echo "Site name set to $site_name. Cannot be empty."
  fi

  echo "Insert your admin email address:"
    read site_mail

    if [ -z "$site_mail" ]
    then
      site_mail='info+siteinstall@reload.dk'
      echo "The email is sent to $site_mail."
    fi


  echo "\$conf['site_name'] = '$site_name';" >> sites/default/common.settings.php

  echo 'Now enter the url to your database (fx. mysql://username:pass@localhost:3306/kaffe): '
  read db_url

  if [ -z "$db_url" ]
  then
    echo "Database url cannot be empty."
  fi


  # Now install the site.
  drush site-install minimal --locale=da --site-name="$site_name" --account-mail="$site_mail" --account-name="$KAFFE_D_USER" --account-pass="$KAFFE_D_PWD" --db-url="$db_url"


  clear
  echo "\n"
  echo "If you wanna use Google Analytics please provide your key now\n(UA-xxxxxxx-yy): "
  read ga_key

  if [ -z "$ga_key" ]
  then
    echo "Remember to configure it later on"
  else
    drush en -y googleanalytics
    drush vset googleanalytics_account "$ga_key"
  fi

  clear
  echo "\n"
  echo "Do you wish to install Development related tools such as devel, stage_file_proxy, diff, etc.:"
  while true; do
    read -p "Choose yes of no (y/n): " yn
    case $yn in
      [Yy]* ) drush en -y devel diff stage_file_proxy reload_dev module_filter;break;;
      [Nn]* ) echo "Alrighty then!";break;;
      * ) echo "Please answer yes or no (y/n)";;
    esac
  done

  clear
  echo "\n"
  echo "Please select your type of spam protection \n1. Mollom\n2. Captcha/reCaptcha\n3. Honeypot"
  read -p "Please select: " spam
    case $spam in
      [1]* ) drush dl -y mollom && drush en -y mollom;break;;
      [2]* ) drush dl -y captcha recaptcha && drush en -y captcha recaptcha;break;;
      [3]* ) drush dl -y honeypot && drush en -y honeypot;break;;
      * ) echo "No spam protection selected";;
    esac

  clear
  echo "\n"
  echo "Do you want to use a preconfigured article content type?"
  while true; do
    read -p "Choose yes of no (y/n): " yn
    case $yn in
      [Yy]* ) drush en -y reload_article;break;;
      [Nn]* ) break;;
      * ) echo "Please answer yes or no (y/n)";;
    esac
  done



}

drush_scripts() {
  # Run some code via drush.
  drush scr "$KAFFE_DIR/resources/scripts/user_roles.drush.php"
  drush scr "$KAFFE_DIR/resources/scripts/vars.drush.php"
}

drush_scripts_post() {
  # Run some code via drush.

  drush en -y reload_editor
  drush secure-permissions-rebuild
  clear
    echo "\n"
    echo "Do you want an editor user to be created (user:editor / pass:editor)?"
    while true; do
      read -p "Choose yes of no (y/n): " yn
      case $yn in
        [Yy]* ) drush scr "$KAFFE_DIR/resources/scripts/create_default_editor_user.drush.php";break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no (y/n)";;
      esac
    done
}

enable_modules() {
  # Enable core modules we want.
  drush en -y block contextual image list menu number options path taxonomy dblog toolbar field_ui file rdf
  # Enable admin theme.
  drush en -y seven
  # Get rid of silly blocks for seven
  drush sql-query "UPDATE block SET region = '-1' WHERE theme = 'seven' AND delta IN('login', 'navigation', 'management')"
  # Enable contrib modules - do it in several rounds to avoid timeouts.
  drush dis -y toolbar && drush en -y admin_menu_toolbar shortcut ultimate_cron
  drush en -y webform jquery_update media wysiwyg linkit pathologic chosen scheduler link clone node_clone_tab smart_trim page_manager
  drush en -y ctools admin_views date ds_extras ds_ui entity entityreference environment_indicator features field_group globalredirect
  drush en -y i18n l10n_update libraries pathauto strongarm token transliteration views views_bulk_operations xmlsitemap_node xmlsitemap_taxonomy
  drush en -y manualcrop watchdog_filtering file_resup
  # Enable our own custom stuff.
  drush en -y reload_f5 reload_media reload_jira_update
}
