<?php
/**
 * @file
 * Tweaks for development use.
 */

/**
 * Implements hook_css_alter().
 */
function reload_dev_css_alter(&$css) {

  // Find the active themes path.
  global $theme_info;

  $theme_path = drupal_get_path('theme', $theme_info->name);

  foreach ($css as $path => &$entry) {
    // $css contains all css files used on the site, here we look for all
    // css files that are located within the used theme. For each file found
    // the path is altered to fetch the dev version of the file.
    if (strpos($path, $theme_path) !== FALSE) {
      if (file_exists(str_replace($theme_info->name . '/css/', $theme_info->name . '/css_dev/', $path))) {
        $entry['data'] = str_replace($theme_info->name . '/css/', $theme_info->name . '/css_dev/', $path);
      }
    }
  }
}
