imports:
  - behat.local.yml
default:
  filters: 
    tags: '~@wip'
  paths:
    features: '%behat.paths.base%/../features'
    bootstrap: '%behat.paths.features%/bootstrap'
  extensions:
    Behat\MinkExtension\Extension:
      show_cmd: 'open %s'
      javascript_session: 'selenium2'
      selenium2:
        browser: firefox
      goutte: ~
      selenium2:
        wd_host: "http://localhost:4444/wd/hub"
    Drupal\DrupalExtension\Extension:
      blackbox: ~
      api_driver: 'drush'
      region_map:
        Primary tabs: 'ul.primary.tabs'
        Main menu: '#main-menu'
      text:
        log_out: "Log ud"
        log_in: "Log ind"
        password_field: "Adgangskode"
        username_field: "Brugernavn"
      subcontexts:
        paths:
          - '%behat.paths.base%/../subcontexts'
